// Turkish (tr) UI strings — generated by scripts/generate-ui-translations.ts
// on 2026-07-13. Safe to hand-edit: re-runs preserve existing
// keys unless --force is used. Missing keys fall back to English at runtime.
import type { UiKey } from './en'

export const uiStrings = {} satisfies Partial<Record<UiKey, string>>
